// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtzpe2OnaAH51i6PFitWAeKfh6SBtwj-k',
    appId: '1:906449779436:web:1a1b2ba1eccf066e4cc3c9',
    messagingSenderId: '906449779436',
    projectId: 'tobuy-ce2e9',
    authDomain: 'tobuy-ce2e9.firebaseapp.com',
    storageBucket: 'tobuy-ce2e9.firebasestorage.app',
    measurementId: 'G-G42VQN85ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp4tCA28jh-S3WIKcS_fg3CemSjYCbkdI',
    appId: '1:906449779436:android:afb92cae5f058de04cc3c9',
    messagingSenderId: '906449779436',
    projectId: 'tobuy-ce2e9',
    storageBucket: 'tobuy-ce2e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_cmA8GNL6qTcvbv0I9XXvlaABn5JUnk',
    appId: '1:906449779436:ios:3194875a762770eb4cc3c9',
    messagingSenderId: '906449779436',
    projectId: 'tobuy-ce2e9',
    storageBucket: 'tobuy-ce2e9.firebasestorage.app',
    iosBundleId: 'com.example.toBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB_cmA8GNL6qTcvbv0I9XXvlaABn5JUnk',
    appId: '1:906449779436:ios:3194875a762770eb4cc3c9',
    messagingSenderId: '906449779436',
    projectId: 'tobuy-ce2e9',
    storageBucket: 'tobuy-ce2e9.firebasestorage.app',
    iosBundleId: 'com.example.toBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtzpe2OnaAH51i6PFitWAeKfh6SBtwj-k',
    appId: '1:906449779436:web:243d26fed2f6286b4cc3c9',
    messagingSenderId: '906449779436',
    projectId: 'tobuy-ce2e9',
    authDomain: 'tobuy-ce2e9.firebaseapp.com',
    storageBucket: 'tobuy-ce2e9.firebasestorage.app',
    measurementId: 'G-338MB590X7',
  );
}
